### ISSUE TITLE
Artifacts in README preview image?

### ISSUE THREAD

**Issue by brylie** [xiph/daala#216]
Are the image artifacts in the README preview image intentional? They are quite eye catching, and might not lend confidence in this compression codec:

![screenshot_20161221_151056](https://cloud.githubusercontent.com/assets/17307/21390469/d3770458-c78f-11e6-9163-776e10ef370f.png)

**Comment by luctrudeau** [comment]
Hi Brylie,

Yes the artifacts are intentional. It even has a name: "Rainbow Vomit Tiger" and you can get it on a t-shirt http://www.zazzle.com/daala_t_shirt-235139149596175944. Contributing patches to Daala is another way of getting such a prized item.

More seriously, people should be confident in the technology behind Daala, from the numerous demos (https://wiki.xiph.org/Daala#Documents) and from Are We Compressed Yet? (https://arewecompressedyet.com).

However, they should not start using this format right now, as it is under development and the syntax is constantly evolving. For example, if tomorrow you pulled the latest version from master you might get a different format from today's master. Hence the slogan: "Another day another Daala".

**Comment by brylie** [comment]
OK, thanks. There is just not much context in the README to explain why the tiger is vomiting.
