### ISSUE TITLE
The block size decision appears broken at higher rates.

### ISSUE THREAD

**Issue by negge** [xiph/daala#67]
Encoding the test image Fruits_oranges,_jardin_japonais_2.y4m using the new block size decision code (commit 214a0d65) with the default quantizer -v 10 gives the following:

http://people.xiph.org/~unlord/fruits-blocks-huh.png

This behavior does not show up at lower rates, e.g., -v 20

**Comment by jmvalin** [comment]
The problem also only occurs when activity masking is enabled. This is due to the fact that the block size RDO distortion metric does not really take into account activity masking (much less than quantization does anyway). Because of that, it tends to select 4x4 blocks much more because 4x4 doesn't have activity masking turned on so it matches the decision metric better.

**Comment by tmatth** [comment]
AM enabled, -v10:
![AM enabled, -v10](http://people.xiph.org/~tmatth/fruit_am_v10_blocks.png)
AM disabled, -v10:
![AM disabled, -v10](http://people.xiph.org/~tmatth/fruit_no_am_v10_blocks.png)
AM enabled, -v20:
![AM enabled, -v20](http://people.xiph.org/~tmatth/fruit_am_v20_blocks.png)
AM disabled, -v20:
![AM disabled, -v20](http://people.xiph.org/~tmatth/fruit_no_am_v20_blocks.png)

**Comment by tmatth** [comment]
It seems like the major improvement happend at commit aa81401f57566f2755d749260fd2c25a38c00f70

**Comment by tmatth** [comment]
Closing since at least we know _when_ it got fixed, albeit not _how_ it got fixed.
